name: CI

# Controls when the action will run.
on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup haxe
      - name: Dependencies
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.x'
          architecture: x64

      # Build haxe code to python.
      - name: Build
        run: |
          haxe -version
          haxe build.hxml

      # Automatically generate a requirements.txt file and import everything from there.
      - name: Generate Requirements
        run: |
          pip install pipreqs
          pipreqs . # Current directory
          pip install -r requirements.txt # Install all modules found

      # Run python code.
      - name: Test Python Code
        run: |
          python wsgi.py ci